:description: Neo4j's GenAI plugin provides functions to interact with external AI providers through Cypher (create vector embeddings, generate text).

= Introduction

Neo4j's GenAI plugin provides functions and procedures to interact with external AI providers through Cypher, such as for creating vector embeddings and generating text.

[NOTE]
To use the plugin's features, you need an account and API credentials from one of the supported external AI providers: (OpenAI, Azure OpenAI, VertexAI, Amazon Bedrock).

[[installation]]
== Installation

**In link:https://neo4j.com/product/auradb/[Neo4j Aura]**, the GenAI plugin is enabled by default.

**On self-managed instances**, you install the plugin by moving the `neo4j-genai.jar` file from `<NEO4J_HOME>/products` to `<NEO4J_HOME>/plugins`, or, if you are using Docker, by starting the Docker container with the extra parameter `--env NEO4J_PLUGINS='["genai"]'`.
For more information, see link:{neo4j-docs-base-uri}/operations-manual/current/configuration/plugins/[Operations Manual -> Configure plugins].
